
# Theme configuration
remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme

minima:
  skin: auto

# Site settings
title: SHFW-Walkthrough
description: Simple guide to get familiar with the basics.
